
name: "TimescaleDB"
slug: "timescaledb"
description: "TimescaleDB - PostgreSQL with time-series capabilities for Home Assistant"
image: "rueda1208/timescaledb:1.0.0"
version: "1.0.0"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
host_network: false
ptions:
  POSTGRES_USER: homeassistant
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: homeassistant
  expose_port: false
schema:
  POSTGRES_USER: str
  POSTGRES_PASSWORD: str
  POSTGRES_DB: str
  expose_port: bool
ports:
  5432/tcp: null
map:
  - config:rw
  - ssl:ro
  - share:rw
environment:
  TZ: UTC