build_from:
  aarch64: "arm64v8/ghcr.io/home-assistant/amd64-base:3.19"
  amd64: "amd64/ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "arm32v7/ghcr.io/home-assistant/amd64-base:3.19"
  i386: "i386/ghcr.io/home-assistant/amd64-base:3.19"