name: "Telegraf"
description: "Telegraf add-on with modular configuration"
slug: "telegraf_configurable"
version: "1.0.0"
init: false
arch:
  - aarch64
  - amd64
  - arm64
  - armv7
  - i386
boot: auto
startup: services
host_network: false
homeassistant_api: true
